### ISSUE TITLE
MYBATIS CALLABLE 이슈

### ISSUE THREAD

**Issue by RohMoon** [geundu/KOSMO80_FINAL#15]
**_1.  CUD 관련 기능 컨트롤러에서 DAO클래스에서 프로시저가 정상적으로 작동 되지 않던 부분 확인 됨._**

![CALLABLE3](https://user-images.githubusercontent.com/78711148/125746791-78426518-3077-42c7-8d75-e38c3634a8fb.PNG)

**_2.  컨트롤러 및 확인 결과_**

![CALLABLE](https://user-images.githubusercontent.com/78711148/125746858-553b642d-bc98-4888-b4d2-1c2b633fefb3.PNG)
 - MAPPER 파일을 보면 속성에   statementType="CALLABLE" 이 빠져있음이 확인됨.

 - 'DEFAULT값은 "PREPARED" 이고, STATEMENT,CALLABLE 로 설정가능하지만, 
    DEFAULT의 경우 SELECT, INSERT, UPDATE, DELETE를 하는 프로시저가 아닌 DML문에서 사용하고,
   프로시저를 사용하는 경우,  CALLABLE을 사용하여 프로시저로 인식을 해주어야 수행이 가능함. 

 - 변경 후 결과  
![CALLABLE2](https://user-images.githubusercontent.com/78711148/125747524-718f88a8-eb44-4523-a79a-70ce1e46939a.PNG)

![CALLABLE4](https://user-images.githubusercontent.com/78711148/125747545-86edc2ee-22e4-4bc1-86dd-e7f1bfff5672.PNG)

**Comment by RNCST** [comment]
코드같은경우 "```" 써서 코드블럭으로좀 올려주세요 


```
이렇게
```

![image](https://user-images.githubusercontent.com/76672259/125757486-0f37462b-8765-4d3f-9f85-255af5002b7a.png)
