### ISSUE TITLE
필드 주입 이슈 Field Injection Issue

### ISSUE THREAD

**Issue by RohMoon** [geundu/KOSMO80_FINAL#9]
# **1. 이슈 발단_및 개요**
  - 이클립스 에서는 경고가 표시되지 않지만,
  IntelliJ 사용시 해당 프로젝트에서 Field Injection  사용을 위한 Annotation @AutoWired에 경고가 나타남.
 해당 내용 확인 후, 자바 소스 코드 방식 변경. 

#### 그림1.      IntelliJ 내부에서 나타내는 경고 문구._
<img width="1023" alt="인젝션방법 1" src="https://user-images.githubusercontent.com/78711148/124881570-76a8c980-e00a-11eb-84eb-692a005e6d80.png">

#### 그림2   생성자 주입으로 변경된 코드 .
<img width="505" alt="생성자 주입1" src="https://user-images.githubusercontent.com/78711148/124882436-562d3f00-e00b-11eb-89b7-f347337e9f0f.PNG">

#   2.  필드 주입법을 왜 변경했는지 설명에 앞서
먼저,
 스프링 사용 시 '의존 관계 주입' ,'Dependency Injection' (이하 DI) 을 알아야 하는데. 
이 DI는 사실 스프링 사용 시 뿐이 아닌 객체 지향 프로그래밍에서는 항상 빠지지 않는 개념이고,

 이것을 어떻게 사용하는 지에 따라서 결합도가 높아질수도, 낮아 질수도 있고 런타임시에
의존관계가  결정되기도 한다는 것을 상기 해야 한다.

 스프링에서는 크게 3가지 방법이 있고 각각,
필드(Field) 주입법, 세터(수정자) 주입법, 생성자(Const) 주입법 이다.

아래부터 각각 설명 하자면 

#### 그림3.  필드 주입 코드 , 노란색 밑줄이 경고(추천사항)을 나타내고 있다. 
<img width="550" alt="인젝션이슈2" src="https://user-images.githubusercontent.com/78711148/124882002-eb7c0380-e00a-11eb-8157-53a76f450e4e.PNG">

 - 간단하게 사용 할 수 있는 방법으로, 연결되는 클래스 즉 패턴상 다음 흐름이 되는 클래스를 선언하고 ,
 - 그 위에 @Autowired를 붙여주면 자동으로 의존성 주입을 해준다.
  

##   B. 수정자 주입(Setter Injection)
 - 해당 방법은 선언된 흐름이 되는 클래스의 Setter  메소드를 생성해서 사용 한다.
 - 해당 방법은 꼭 Setter 메서드가 아니어도 된다. 
 - 메서드의 내용 / 파라미터는 동일해야한다.
 
 

##  C. 생성자 주입(Constructor Injection)
 -  스프링 자체에서 권장하는 방식.
 -  스프링 프레임워크 4.3 버젼 이상 에서는 의존성 주입으로 클래스를 완벽하게 분리 가능.
 - 단일 생성자인 경우 @Autowired 를 붙이지 않아도 되지만, 생성자가 2개 이상이라면 어노테이션을 붙여야한다.

# 3.  왜 필드 주입법에서 생성자 주입법으로 변경을 했는가
##  A . 순환 참조를 방지 한다.
   * 순환 참조 ? 

#### 그림 4
![순환참조](https://user-images.githubusercontent.com/78711148/124922042-0d3db080-e034-11eb-929e-774d699bd42b.png)

```
예로 들면,
Bean A -> Bean B -> Bean A 처럼 계속 여러 빈들이 서로 물고 늘어져서 계속 연결되는 것을 의미한다.
A가 B에 필요한데, 또 B는 A가 필요한 상태가 생길 수 있다는 것이다. 
  
```
또 다른 예로 Bean A -> Bean B -> Bean C 처럼 연결되어 있다고 하면 
스프링은 A를 먼저 생성하고
 A를 필요로 하는 B를 만들고
 B를 필요로하는 C를 생성하게 된다.
하지만 순환 참조가 발생시 스프링은 어떤 빈을 먼저 어떻게 생성해야할지 
결정을 못 한다는 에러를 나타내주고 실행이 되지 않는다.
 
하지만 필드 주입시 해당 에러를 판단하지 못하고 실행하게 실행되고 실제 코드 호출 전까지는 문제를 발견 할 수 없다.
            
```
하지만 생성자 주입법을 사용한다면  실행시에 참조에러를 나타내어 사전에 확인 할 수 있다 .

! 이러한 경우 설계가 잘못되어 변경을 해야하지만, 여의치 않다면
@Lazy를 이용해서 해결을 " 시도해볼 수는 있다고 한다."
```

<a href='https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.lazy-initialization' target='_blank'>
 SpringBoot Features Document - 1.2. Lazy Initialization
</a>

<img width="317" alt="순환참조3" src="https://user-images.githubusercontent.com/78711148/124925083-0f553e80-e037-11eb-9ae3-d71092cbc90d.PNG">
```
"시도를 해볼 수 있다." 라고 하는 것 앱 기동시점이 아닌 실제 해당 빈이 필요한 시점에 빈을 생성하기 때문에
특정 http 요청을 받았을 경우 힙메모리가 증가할 가능성이 높으며, 메모리가 충분하지 않는 상황이라면 서비스에 장애가 생기는  결과를 야기할 수 있다고 한다. 
```
##  B. 빈을 주입하는 순서가 다르다.
  - 필드 주입의 경우 빈을 생성하고 어노테이션이 붙은필드에 해당하는 빈을 찾아서 주입한다. 
                   (빈을 생성 -> 필드에 대해 주입)
  - 세터 주입은 주입 받으려는 빈의 생성자를 호출해서 빈을 찾거나 빈 팩토리에 등록 후에 생성자 인자에 사용해서
     빈을 찾거나 생성하고 이 후 수정자를 호출해서 주입한다.

  - 생성자 주입의 경우에는 _생성자로 객체를 생성하는 시점에 필요한 빈을 주입_한다. 
      생성자의 인자에 사용 되는 빈을 찾음 / 빈 팩토리에서 만듬 ->    찾은 인자 빈으로 주입하려는 빈의 생성자를 호출 
              **_먼저 빈을 생성하지 않는다._**         세터 주입과 다른 부분이다. 
              이러한 이유로 생성자 주입에서만 문제가 된다.    
             다르게 설명하자면 , 
               객체 생성 시점에 빈을 주입하기 때문에 서로 참조하는 객체가 생성되지 않은 상태에서
                   해당 빈을 참조하기 때문에 오류가 발생하는 것이라고 생각하면 된다.
```
 분명, ' 순환 오류를 피하려면 다른 주입법을 사용해도 되지 않아?' 라고 생각하는 부분도 있을텐데,
오히려 순환 참조가 있는 설계는 잘못되었기 때문에 오히려 생성자 주입을 사용해서 사전에 방지한다는 효과가 있다고 하 
는 것이다. 
```
## C. 테스트에 용이하다 .
  - DI 의 핵심 관리되는 클래스가 DI  컨테이너에 의존성이 없어야 한다. 이다. 
   독립적으로 인스턴스화가 가능한 POJO 여야 한다는 것.
    DI 컨테이너를 사용하지 않아도 단위 테스트에서 인스턴스가 가능하다면 테스트가 용이하다. 

#### 그림 5 
<img width="314" alt="참조44" src="https://user-images.githubusercontent.com/78711148/124927624-ceaaf480-e039-11eb-949e-28331c459994.PNG"> 

 위의 그림과 같은 상황이 해당 프로젝트에서는 일어나지 않을테지만, 이러한 상황에서 정리가 가능하다는 장점도 있다. 

##  E. 오류 방지
 - 스프링 레퍼런스에서 강제화 되는 의존성의 경우는 생성자 주입 형태를 사용하고 선택적인 경우에
   세터 주입 형태를 사용하는 것을 권장하고 있다.
   불변 객체나 null이 아니라는 것을 보장할 때는 반드시 생성자 주입을 사용해야 한다.
   그림 1에서 final을 주는 이유이다.  해당 경우 값을 변경할 수 없는 특성이 있다.
  필드 주입을 사용 하면 선언된 필드는 final이 아니게 된다.
따라서 런타임 시점에 변경이 가능하고, null참조하는 경우 nullPointException 을 일으키게 된다. 
   생성자 주입상요 한다면 컴파일 시점에서 미리 오류를 확인 할 수 있다.

**Comment by geundu** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.spring-beans-and-dependency-injection

해당 섹션도 참고하시면 좋을 거 같습니다.
